# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insure', '0003_auto_20180527_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
