# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'verbose_name': '\u51fa\u9669', 'verbose_name_plural': '\u51fa\u9669'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '\u56fe\u7247', 'verbose_name_plural': '\u56fe\u7247'},
        ),
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'verbose_name': '\u4fdd\u9669\u516c\u53f8', 'verbose_name_plural': '\u4fdd\u9669\u516c\u53f8'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '\u4e8b\u53d1\u5730\u70b9', 'verbose_name_plural': '\u4e8b\u53d1\u5730\u70b9'},
        ),
        migrations.AlterField(
            model_name='claim',
            name='accident_type',
            field=models.CharField(choices=[('danche', '\u5355\u8f66\u4e8b\u6545'), ('guaca', '\u4e24\u8f66\u522e\u64e6\u4e8b\u6545'), ('zhuiwei', '\u4e24\u8f66\u8ffd\u5c3e\u4e8b\u6545')], max_length=20, verbose_name='\u51fa\u9669\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='car_plate',
            field=models.CharField(max_length=200, verbose_name='\u8f66\u724c\u53f7'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claim.InsuranceCompany', verbose_name='\u6295\u4fdd\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='location',
            field=models.CharField(max_length=200, verbose_name='\u51fa\u9669\u5730\u70b9'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='time',
            field=models.CharField(max_length=200, verbose_name='\u51fa\u9669\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='user.User', verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='image',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='claim.Claim', verbose_name='\u51fa\u9669\u8bb0\u5f55'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='claims', verbose_name='\u56fe\u50cf\u8bb0\u5f55'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies_logo/', verbose_name='\u516c\u53f8Logo'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u516c\u53f8\u7f51\u5740'),
        ),
    ]
