# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_auto_20180527_0437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'verbose_name': '\u51fa\u9669\u8bb0\u5f55', 'verbose_name_plural': '\u51fa\u9669\u8bb0\u5f55'},
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='NAME', max_length=120, verbose_name='\u56fe\u50cf\u540d\u79f0'),
            preserve_default=False,
        ),
    ]
