# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_auto_20170908_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='car_plate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
