# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0006_auto_20171202_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='plate',
            new_name='car_plate',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='car_plate',
        ),
        migrations.AddField(
            model_name='claim',
            name='accident_type',
            field=models.CharField(choices=[('danche', '\u5355\u8f66\u4e8b\u6545'), ('guaca', '\u4e24\u8f66\u522e\u64e6\u4e8b\u6545'), ('zhuiwei', '\u4e24\u8f66\u8ffd\u5c3e\u4e8b\u6545')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='step',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
