# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('national_id_number', models.CharField(max_length=200, unique=True)),
                ('driver_license_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
