# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '\u8f66\u5e2e\u624b\u7528\u6237', 'verbose_name_plural': '\u8f66\u5e2e\u624b\u7528\u6237'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_license_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u7535\u8bdd'),
        ),
    ]
